### ISSUE TITLE
quick order

### ISSUE THREAD

**Issue by findaskip** [forefrontdigital/FindASkip-issues#1]
Can this be call quick quote

If no results for size can it show results for other sizes if available?

Permits:  delivery  / collection date (date should not be historic dates)

Permits can a box show the number of days taken to arrange per supplier and cost

Can you create an order from this page

When you click through to the supplier, you should be able to create order.

What does assign order do in supplier side?

Whats happened to unpaid suppliers section?

Front end

Should not be able to order a skip for current day

Change date format

booking process:

i think the booking process could be simplified to the following:
post code 
skip size
permit y/n 
price

If they then want to book, select dates ,waste types etc...
What do you think?

Booking form should be delivery address first

tick box for billing address different to delivery, only if this is ticked should billing address form show.

Do we need a star for both city & county?

if you do not fill in all starred fields and click on book and pay, it does not tell you that fields are missing and you cannot continue.

I created 4970 the supplier is JBT Waste services ltd, the dashboard is showing as JBT123?

Can we see delivery date on most recent orders dashboard
View order 4970 mobile number is missing "0"
Edit order, if you change something and press save, the waste type disappears.
i added a waste type, pressed save and I got an error message

**Comment by eqxDev** [comment]
Moved into the following issues for organisation:
https://github.com/forefrontdigital/FindASkip-issues/issues/2
https://github.com/forefrontdigital/FindASkip-issues/issues/4
https://github.com/forefrontdigital/FindASkip-issues/issues/3
