### ISSUE TITLE
Supplier Area Details

### ISSUE THREAD

**Issue by eqxDev** [forefrontdigital/FindASkip-issues#14]
http://admin.findaskip.co.uk/supplier-area/create?supplier_id=54

Make it work.

Postcodes selected *unique* to that specific area for that supplier.

You can only add the skip prices once created then edit.

http://admin.findaskip.co.uk/supplier-area/219/edit "Supplier Preferences" changed to "Skip Prices"

**Comment by findaskip** [comment]
We need to be able to see when a supplier logged in to the portal or clicked on an email confirmation or declined.

**Comment by eqxDev** [comment]
Creating a new job for this.
