### ISSUE TITLE
Unpaid / paid Suppliers Report

### ISSUE THREAD

**Issue by findaskip** [forefrontdigital/FindASkip-issues#16]
Can we have a report to show history of unpaid suppliers that we pay.

Need to be able to select dates so that we can see who was paid and when?

**Comment by eqxDev** [comment]
So a report of suppliers that you have not paid?

An export of this maybe? http://admin.findaskip.co.uk/supplier-unpaid

**Comment by findaskip** [comment]
A report of suppliers we have paid using the un-paid supplier tab.  A history of this.

**Comment by eqxDev** [comment]
Page select two dates then it will create an export of all suppliers paid in that time. Need to add to database paid date.

**Comment by eqxDev** [comment]
Add data paid to order and then create report of when an order was paid.

**Comment by eqxDev** [comment]
Done.
