### ISSUE TITLE
Editing Customer Orders

### ISSUE THREAD

**Issue by findaskip** [forefrontdigital/FindASkip-issues#18]
When editing customer orders the quotation box is all at zero ?

These figures need to show what the customer has paid and they must be amendable.
We also need to add a cost box, for miscellaneous costs, with a notes box.   For example if the supplier turns up with the skip and cannot deliver as the access was poor.  We may have to refund the customer part of the money back but they may to pay a wasted journey fee.

**Comment by eqxDev** [comment]
http://admin.findaskip.co.uk/order/4871/edit?account_id=13

Sending the API request just not updating.

**Comment by eqxDev** [comment]
JavaScript: update(238);

Update ID is not being run on load.

**Comment by eqxDev** [comment]
Done.

**Comment by findaskip** [comment]
cant see miscellaneous box in the quotation box
