### ISSUE TITLE
General Backend fixes.

### ISSUE THREAD

**Issue by eqxDev** [forefrontdigital/FindASkip-issues#2]
Can this be call quick quote

If no results for size can it show results for other sizes if available?

Permits: delivery / collection date (date should not be historic dates)

Permits can a box show the number of days taken to arrange per supplier and cost

Can you create an order from this page

When you click through to the supplier, you should be able to create order.

What does assign order do in supplier side?

Whats happened to unpaid suppliers section?

**Comment by findaskip** [comment]
- When you hover over a supplier in an order or on the dashboard can the supplier phone number appear?

Supplier jobs can we see the first line of the customer delivery address.

Unpaid suppliers, can we see the totals we have highlighted to be paid (supplier fee total only)

**Comment by eqxDev** [comment]
Quick order finished.
