### ISSUE TITLE
exchange account order

### ISSUE THREAD

**Issue by findaskip** [forefrontdigital/FindASkip-issues#20]
These errors appear when you exchange:

The lastname field is required.
The billing city field is required.
The billing county field is required.
The delivery city field is required.
The delivery county field is required.

status set to failed
Exchange orders are not shown on account orders.  (blue exchange tab)

**Comment by eqxDev** [comment]
That is probably because in the old system these fields are not required. I can make it so they are not required if you like?

**Comment by findaskip** [comment]
No I think the fields were blank on the original order used.
