### ISSUE TITLE
Supplier Payment Method

### ISSUE THREAD

**Issue by findaskip** [forefrontdigital/FindASkip-issues#23]
On current orders we have Supplier paid y/n

we need to have more options for yes:  BACS, CQ, Debit card, credit card, invoice

This also needs to be reflected in the reporting side.

**Comment by findaskip** [comment]
supplier side needs to have a box to show how supplier is to be paid options are: 
pay as we go
account
invoice

**Comment by eqxDev** [comment]
Will add the options.

How does this second comment work: 
"supplier side needs to have a box to show how supplier is to be paid options are:
pay as we go
account
invoice"

**Comment by findaskip** [comment]
So in the supplier admin side, we see how the supplier is normally paid for orders.

**Comment by eqxDev** [comment]
Replace Yes and No with the following: BACS, CQ, Debit card, credit card, No

**Comment by eqxDev** [comment]
Done.

**Comment by findaskip** [comment]
cant see invoiced as an order status.
