### ISSUE TITLE
emails

### ISSUE THREAD

**Issue by findaskip** [forefrontdigital/FindASkip-issues#25]
We should be able to resend the emails from the order section.  Also generate emails for non suppliers with order details.

**Comment by findaskip** [comment]
Customer email should have order number and all delivery details to ensure they have typed the correct information.

**Comment by eqxDev** [comment]
Option to resend the email to the client confirmation.
----
Resend the email to the supplier if it is still pending (should update supplier if changed)
----

If supplier is Admin then you are asked manually to have the suppliers email in the order.

----

extra weight email template taking information from the order and sent via a notification.

**Comment by eqxDev** [comment]
Done. Will make another job for the extra weight.
