### ISSUE TITLE
edit new admin order 4981

### ISSUE THREAD

**Issue by findaskip** [forefrontdigital/FindASkip-issues#45]
if admin order, when you edit it the admin supplier disappears and you get an error page.

**Comment by eqxDev** [comment]
http://admin.findaskip.co.uk/api?action=get-price&auth=2323f0a71002dc4b05d1f25d6ea79cfd&skipsize=2&durationDays=-1&postcode=s81+3ds&supplier=-1&sort=true&_=1513267965425

Admin not showing up as a option.
