### ISSUE TITLE
order time

### ISSUE THREAD

**Issue by findaskip** [forefrontdigital/FindASkip-issues#55]
the time an order was created needs to be shown on each new order.

**Comment by eqxDev** [comment]
On which page would you like it to show time as well?

**Comment by findaskip** [comment]
This is how it is displayed in the current back end. 
10/01/2018 (14:16)

**Comment by eqxDev** [comment]
I can only put this on the dashboard for recent orders is that okay?

**Comment by eqxDev** [comment]
Done.
