### ISSUE TITLE
disabled supplier skip size / supplier

### ISSUE THREAD

**Issue by findaskip** [forefrontdigital/FindASkip-issues#70]
I disabled thurston waste 2 yard skip in ss7 area, but frontend still gave quote for them and on quick quote it is showing (it should be highlighted as disabled)

**Comment by findaskip** [comment]
I also disabled the supplier with the same result, still had a quote from them on the frontend and showing on quick quote (should be highlighted)

**Comment by eqxDev** [comment]
Done.
