### ISSUE TITLE
Dashboard Phone Number

### ISSUE THREAD

**Issue by eqxDev** [forefrontdigital/FindASkip-issues#9]
http://admin.findaskip.co.uk/

On the suppliers hover for phone number like flag reason.

**Comment by findaskip** [comment]
Also be able to click straight through to the supplier from an order on the dashboard, rather than go to supplier area to find supplier.

**Comment by eqxDev** [comment]
Added phone number.

Do you mean to be able to click the supplier name then it takes you to the supplier page?

**Comment by findaskip** [comment]
yes

**Comment by eqxDev** [comment]
Done
